#include "RNOH/PackageProvider.h"
#include "generated/RNOHGeneratedPackage.h"
#include "BaseReactNativeWechatLibPackage.h"
#include "RNImagePickerPackage.h"

using namespace rnoh;

std::vector<std::shared_ptr<Package>> PackageProvider::getPackages(
    Package::Context ctx) {
  return {
      std::make_shared<RNOHGeneratedPackage>(ctx), // generated by codegen v1
      std::make_shared<BaseReactNativeWechatLibPackage>(ctx),
      std::make_shared<RNImagePickerPackage>(ctx),
  };
}